language: csharp

addons:
  coverity_scan:
    project:
      name: "WhiteCoreWebUI/WhiteCore-Dev"
      description: "Build submitted via Travis CI"
    notification_email: k.meerts89@gmail.com
    build_command_prepend: "./runprebuild.sh -c Debug -a x64 -b Yes"
    build_command:   "xbuild"
    branch_pattern: master
    
mono:
  - latest
script:
  - ./runprebuild.sh -c Debug -a x64 -b Yes
notifications:
  irc:
    channels:
      - "chat.freenode.net#whitecore-dev#WhiteCoreAdv"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
sudo: false
