version: 0.9.4.{build}
branches:
  only:
  - master
build_script:
- Prebuild.exe /target vs2010 /targetframework v4_5 /conditionals ISWIN;NET_4_5
- msbuild WhiteCore.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_5"
artifacts:
- path: WhiteCoreSim\bin
  name: WhiteCore
  notifications:

  - provider: Webhook
    url: http://n.tkte.ch/h/4867/zR54Lpkq8qmePRJIOT7cjq2q
    method: GET
